# Header
menu:
  Home: /
  Archives: /archives
  今日头条: https://www.toutiao.com/c/user/token/Cibf0kTMq10UYLuwC3D481ty9pEVFfRiwaLVAONHJ7bSWryMSrcmORpJCjwAAAAAAAAAAAAAT1y8wK8rpRaXR_Iouqwd0Lsz2NJLCNgJTOrKJK0pWR78E4A2pp6hkG-A3AHXVu1BI2AQuM_5DRjDxYPqBCIBA8C-KPo=/?tab=all
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
